language: php

php:
  - 7.3

before_script:
  - make up-testing

script:
  - make test-testing

notifications:
  email:
    on_success: never
    on_failure: never
  slack: tabescore:6HPvZVbQMknO1gtwiWeMfmuW