version: '3'

services:
  tabescore:
    container_name: tabescore
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/home/tabescore:cached
      - /home/tabescore/vendor
    ports:
      - 8080:80